default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: packer_dev

test:
  <<: *default
  database: packer_test

production:
  <<: *default
  database: packer_prod
